<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ShortsPrep</AssemblyName>
    <RootNamespace>ShortsPrep</RootNamespace>
    <Product>TrimVideos (ShortsPrep)</Product>
    <Company>herocraftlol</Company>
    <Authors>herocraftlol</Authors>
    <Copyright>Copyright © herocraftlol</Copyright>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <InformationalVersion>1.0.0</InformationalVersion>
    <ApplicationIcon></ApplicationIcon>
    <Platforms>x64</Platforms>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
  </ItemGroup>

</Project>
